### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jowilksasella** [HeiTang/AniCat-v2#2]
Traceback (most recent call last):
  File "e:\Downloads\AniCat-v2-main\AniCat-v2-main\anime1.py", line 118, in <module>
    Anime_Episode(url)
  File "e:\Downloads\AniCat-v2-main\AniCat-v2-main\anime1.py", line 44, in Anime_Episode
    url = soup.find('iframe').get('src')

出現了這個錯誤，是不能用了嗎

**Comment by HeiTang** [comment]
Anime1.me 的前端有進行更動，因此無法順利取得資料，稍晚會進行更新，感謝你的回報。
